#pragma once

#define PROJECT_VERSION "@CMAKE_PROJECT_VERSION@"
#define PROJECT_NAME "@CMAKE_PROJECT_NAME@"



#define PROJECT_VERSION_MAJOR @CMAKE_PROJECT_VERSION_MAJOR@
#define PROJECT_VERSION_MINOR @CMAKE_PROJECT_VERSION_MINOR@
#define PROJECT_VERSION_PATCH @CMAKE_PROJECT_VERSION_PATCH@
#define PROJECT_VERSION_TWEAK @CMAKE_PROJECT_VERSION_TWEAK@
